# Intialisation Steps
Connecting to Snowflake

## Importing required modules

In [1]:
import pandas as pd
from drg_connect import Snowflake
import qgrid 
from datetime import timedelta, datetime
import math

import warnings
warnings.filterwarnings('ignore')

## Snowflake connection parameter

In [2]:
##defining parameters of snowflake
snow = Snowflake(role = 'RWD_ANALYTICS_RW',database='SANDBOX_ANALYTICS',schema = 'SANDBOX')
engine = snow.engine

%reload_ext sql_magic
%config SQL.output_result = True  #Enable output to std out
%config SQL.notify_result = False #disable browser notifications
%config SQL.conn_name = 'engine'  #Set the sql_magic connection engine

# Queries from here

# Checking Raven for CKD (stage 3)

In [3]:
snow.select("select * from RWD_DB.RWD.ICD_GROUPER limit 3")

Initiating login request with your identity provider. A browser window should have opened for you to complete the login. If you can't see it, check existing browser windows, or your OS settings. Press CTRL+C to abort and try again...

,id,level_1,level_1_description,level_2,level_2_description,level_3,level_3_description,level_4,icd9_mapped_codes,icd9_description,level_4_short_description_icd10,level_4_long_description_icd10,create_ts,update_ts
0,1,A00 - B999,Certain infectious and parasitic diseases,A00-A09,Intestinal infectious diseases,A00-A009,Cholera,A00,No map,No map,Cholera,Cholera,2017-11-02,2017-11-02
1,2,A00 - B999,Certain infectious and parasitic diseases,A00-A09,Intestinal infectious diseases,A00-A009,Cholera,A000,0010,Cholera due to vibrio cholerae,Cholera due to Vibrio cholerae 01 biovar cholerae,Cholera due to Vibrio cholerae 01 biovar cholerae,2017-11-02,2017-11-02
2,3,A00 - B999,Certain infectious and parasitic diseases,A00-A09,Intestinal infectious diseases,A00-A009,Cholera,A001,0011,Cholera due to vibrio cholerae el tor,Cholera due to Vibrio cholerae 01 biovar eltor,Cholera due to Vibrio cholerae 01 biovar eltor,2017-11-02,2017-11-02

In [4]:
%%read_sql

select
    *
from
    RWD_DB.RWD.ICD_GROUPER
where
    level_4_short_description_icd10 ilike '%chronic%'
    and level_4_short_description_icd10 ilike '%kidney%'
    and level_4_short_description_icd10 ilike '%disease%'

Query started at 12:44:50 PM India Standard Time; Query executed in 0.05 m

,id,level_1,level_1_description,level_2,level_2_description,level_3,level_3_description,level_4,icd9_mapped_codes,icd9_description,level_4_short_description_icd10,level_4_long_description_icd10,create_ts,update_ts
0,3445,D50 - D899,Diseases of the blood and blood-forming organs...,D60-D64,Aplastic and other anemias and other bone marr...,D63-D638,Anemia in chronic diseases classified elsewhere,D631,28521,Anemia in chronic kidney disease,Anemia in chronic kidney disease,Anemia in chronic kidney disease,2017-11-02,2017-11-02
1,3723,E00 - E8989,Endocrine nutritional and metabolic diseases,E08-E13,Diabetes mellitus,E08-E089,Diabetes mellitus due to underlying condition,E0822,No map,No map,Diabetes due to undrl cond w diabetic chronic ...,Diabetes mellitus due to underlying condition ...,2017-11-02,2017-11-02
2,3839,E00 - E8989,Endocrine nutritional and metabolic diseases,E08-E13,Diabetes mellitus,E09-E099,Drug or chemical induced diabetes mellitus,E0922,No map,No map,Drug/chem diabetes w diabetic chronic kidney d...,Drug or chemical induced diabetes mellitus wit...,2017-11-02,2017-11-02
3,3952,E00 - E8989,Endocrine nutritional and metabolic diseases,E08-E13,Diabetes mellitus,E10-E109,Type 1 diabetes mellitus,E1022,No map,No map,Type 1 diabetes mellitus w diabetic chronic ki...,Type 1 diabetes mellitus with diabetic chronic...,2017-11-02,2017-11-02
4,4068,E00 - E8989,Endocrine nutritional and metabolic diseases,E08-E13,Diabetes mellitus,E11-E119,Type 2 diabetes mellitus,E1122,No map,No map,Type 2 diabetes mellitus w diabetic chronic ki...,Type 2 diabetes mellitus with diabetic chronic...,2017-11-02,2017-11-02
5,4184,E00 - E8989,Endocrine nutritional and metabolic diseases,E08-E13,Diabetes mellitus,E13-E139,Other specified diabetes mellitus,E1322,No map,No map,Oth diabetes mellitus with diabetic chronic ki...,Other specified diabetes mellitus with diabeti...,2017-11-02,2017-11-02
6,10843,I00 - I999,Diseases of the circulatory system,I10-I16,Hypertensive diseases,I12-I129,Hypertensive chronic kidney disease,I12,No map,No map,Hypertensive chronic kidney disease,Hypertensive chronic kidney disease,2017-11-02,2017-11-02
7,10845,I00 - I999,Diseases of the circulatory system,I10-I16,Hypertensive diseases,I12-I129,Hypertensive chronic kidney disease,I129,40300,Hypertensive chronic kidney disease malignant ...,Hypertensive chronic kidney disease w stg 1-4/...,Hypertensive chronic kidney disease with stage...,2017-11-02,2017-11-02
8,10846,I00 - I999,Diseases of the circulatory system,I10-I16,Hypertensive diseases,I13-I132,Hypertensive heart and chronic kidney disease,I13,No map,No map,Hypertensive heart and chronic kidney disease,Hypertensive heart and chronic kidney disease,2017-11-02,2017-11-02
9,10848,I00 - I999,Diseases of the circulatory system,I10-I16,Hypertensive diseases,I13-I132,Hypertensive heart and chronic kidney disease,I131,No map,No map,Hypertensive heart and chronic kidney disease ...,Hypertensive heart and chronic kidney disease ...,2017-11-02,2017-11-02
10,23565,N00 - N9989,Diseases of the genitourinary system,N17-N19,Acute kidney failure and chronic kidney disease,N18-N189,Chronic kidney disease (CKD),N18,No map,No map,Chronic kidney disease (CKD),Chronic kidney disease (CKD),2017-11-02,2017-11-02
11,23566,N00 - N9989,Diseases of the genitourinary system,N17-N19,Acute kidney failure and chronic kidney disease,N18-N189,Chronic kidney disease (CKD),N181,5851,Chronic kidney disease Stage I,Chronic kidney disease stage 1,Chronic kidney disease stage 1,2017-11-02,2017-11-02
12,23567,N00 - N9989,Diseases of the genitourinary system,N17-N19,Acute kidney failure and chronic kidney disease,N18-N189,Chronic kidney disease (CKD),N182,5852,Chronic kidney disease Stage II (mild),Chronic kidney disease stage 2 (mild),Chronic kidney disease stage 2 (mild),2017-11-02,2017-11-02
13,23568,N00 - N9989,Diseases of the genitourinary system,N17-N19,Acute kidney failure and chronic kidney disease,N18-N189,Chronic kidney disease (CKD),N183,5853,Chronic kidney disease Stage III (moderate),Chronic kidney disease stage 3 (moderate),Chronic kidney disease stage 3 (moderate),2017-11-02,2017-11-02
14,23569,N00 - N9989,Diseases of the genitourinary system,N17-N19,Acute kidney failure and chronic kidney disease,N18-N189,Chronic kidney disease (CKD),N184,5854,Chronic kidney disease Stage IV (severe),Chronic kidney disease stage 4 (severe),Chronic kidney disease stage 4 (severe),2017-11-02,2017-11-02
15,23570,N00 - N9989,Diseases of the genitourinary system,N17-N19,Acute kidney failure and chronic kidney disease,N18-N189,Chronic kidney disease (CKD),N185,5855,Chronic kidney disease Stage V,Chronic kidney disease stage 5,Chronic kidney disease stage 5,2017-11-02,2017-11-02
16,23572,N00 - N9989,Diseases of the genitourinary system,N17-N19,Acute kidney failure and chronic kidney disease,N18-N189,Chronic kidney disease (CKD),N189,5859,Chronic kidney disease unspecified,Chronic kidney disease unspecified,Chronic kidney disease unspecified,2017-11-02,2017-11-02
17,24457,O00 - O9A53,Pregnancy childbirth and the puerperium,O10-O16,Edema proteinuria and hypertensive disorders i...,O10-O109,Pre-existing hypertension compl preg/chldbrth,O102,No map,No map,Pre-existing hyp chronic kidney disease compl ...,Pre-existing hypertensive chronic kidney disea...,2017-11-02,2017-11-02
18,24458,O00 - O9A53,Pregnancy childbirth and the puerperium,O10-O16,Edema proteinuria and hypertensive disorders i...,O10-O109,Pre-existing hypertension compl preg/chldbrth,O1021,No map,No map,Pre-existing hyp chronic kidney disease comp p...,Pre-existing hypertensive chronic kidney disea...,2017-11-02,2017-11-02
19,24459,O00 - O9A53,Pregnancy childbirth and the puerperium,O10-O16,Edema proteinuria and hypertensive disorders i...,O10-O109,Pre-existing hypertension compl preg/chldbrth,O10211,64221,Other pre-existing hypertension complicating p...,Pre-exist hyp chronic kidney disease comp preg...,Pre-existing hypertensive chronic kidney disea...,2017-11-02,2017-11-02
20,24460,O00 - O9A53,Pregnancy childbirth and the puerperium,O10-O16,Edema proteinuria and hypertensive disorders i...,O10-O109,Pre-existing hypertension compl preg/chldbrth,O10212,64221,Other pre-existing hypertension complicating p...,Pre-exist hyp chronic kidney disease comp preg...,Pre-existing hypertensive chronic kidney disea...,2017-11-02,2017-11-02
21,24461,O00 - O9A53,Pregnancy childbirth and the puerperium,O10-O16,Edema proteinuria and hypertensive disorders i...,O10-O109,Pre-existing hypertension compl preg/chldbrth,O10213,64221,Other pre-existing hypertension complicating p...,Pre-exist hyp chronic kidney disease comp preg...,Pre-existing hypertensive chronic kidney disea...,2017-11-02,2017-11-02
22,24462,O00 - O9A53,Pregnancy childbirth and the puerperium,O10-O16,Edema proteinuria and hypertensive disorders i...,O10-O109,Pre-existing hypertension compl preg/chldbrth,O10219,64220,Other pre-existing hypertension complicating p...,Pre-exist hyp chronic kidney disease comp preg...,Pre-existing hypertensive chronic kidney disea...,2017-11-02,2017-11-02
23,24463,O00 - O9A53,Pregnancy childbirth and the puerperium,O10-O16,Edema proteinuria and hypertensive disorders i...,O10-O109,Pre-existing hypertension compl preg/chldbrth,O1022,64221,Other pre-existing hypertension complicating p...,Pre-existing hyp chronic kidney disease comp c...,Pre-existing hypertensive chronic kidney disea...,2017-11-02,2017-11-02
24,24464,O00 - O9A53,Pregnancy childbirth and the puerperium,O10-O16,Edema proteinuria and hypertensive disorders i...,O10-O109,Pre-existing hypertension compl preg/chldbrth,O1023,64224,"Other pre-existing hypertension,complicating p...",Pre-existing hyp chronic kidney disease comp t...,Pre-existing hypertensive chronic kidney disea...,2017-11-02,2017-11-02
25,24466,O00 - O9A53,Pregnancy childbirth and the puerperium,O10-O16,Edema proteinuria and hypertensive disorders i...,O10-O109,Pre-existing hypertension compl preg/chldbrth,O1031,No map,No map,Pre-exist hyp heart and chronic kidney disease...,Pre-existing hypertensive heart and chronic ki...,2017-11-02,2017-11-02
26,24471,O00 - O9A53,Pregnancy childbirth and the puerperium,O10-O16,Edema proteinuria and hypertensive disorders i...,O10-O109,Pre-existing hypertension compl preg/chldbrth,O1032,64221,Other pre-existing hypertension complicating p...,Pre-exist hyp heart and chronic kidney disease...,Pre-existing hypertensive heart and chronic ki...,2017-11-02,2017-11-02

In [6]:
%%read_sql
create or replace table st_ckd1 as
select
    patient_id,
    left(year_of_service, 4) as year,
    claim_number,
    diagnosis,
    diagnosis_sequence
    
from
    RWD_DB.RWD.RAVEN_CLAIMS_SUBMITS_DIAGNOSIS
where
    diagnosis in ('N183')

Query started at 12:51:42 PM India Standard Time; Query executed in 0.56 m

                                status
0  Table ST_CKD1 successfully created.

In [7]:
%%read_sql
select count (distinct patient_id)
from
    st_ckd1
    
where 
    left(patient_id, 5) != 'XXX -'

Query started at 12:53:02 PM India Standard Time; Query executed in 0.05 m

   COUNT (DISTINCT PATIENT_ID)
0                      5878038

In [5]:
%%read_sql df

select
    *
from
    RWD_DB.RWD.PELICAN_E_SNOMED_CONCEPT
limit 3

Query started at 12:50:12 PM India Standard Time; Query executed in 0.07 m

,concept_id,concept_status,fully_specified_name,ctvc_id,snomed_id,is_primitive
0,99380004,10,Toradol IM Injection (product),XUSHt,C-C276C,1
1,227961007,0,Grilled vegeburger (substance),Ub0bb,C-F09AD,1
2,230626007,0,Vibration injury of peripheral nerve (disorder),X00Bl,DD-42032,1

In [8]:
%%read_sql df

select
    *
from
    RWD_DB.RWD.PELICAN_E_SNOMED_CONCEPT
    
where fully_specified_name ilike '%chronic%'
    and fully_specified_name ilike '%kidney%'
    and fully_specified_name ilike '%disease%'

Query started at 12:53:41 PM India Standard Time; Query executed in 0.05 m

,concept_id,concept_status,fully_specified_name,ctvc_id,snomed_id,is_primitive
0,117681000119102,0,Chronic kidney disease stage 1 due to hyperten...,XUmqg,R-FB62F,0
1,129181000119109,0,Chronic kidney disease stage 2 due to hyperten...,XUmo7,R-FB590,0
2,285881000119109,0,Malignant hypertensive chronic kidney disease ...,XUla3,D7-11111,1
3,751000119104,0,Chronic kidney disease stage 1 associated with...,XUmE9,R-FACD3,1
4,96741000119109,0,Hypertensive heart AND chronic kidney disease ...,XUlZU,D7-1110C,1
5,104931000119100,0,Chronic kidney disease due to hypertension (di...,XUmqk,R-FB633,1
6,129161000119100,0,Chronic kidney disease stage 5 due to hyperten...,XUmoA,R-FB593,0
7,285861000119100,0,Malignant hypertensive chronic kidney disease ...,XUlZZ,D7-1110E,1
8,96701000119107,0,Hypertensive heart AND chronic kidney disease ...,XUmqd,R-FB62C,1
9,433144002,0,Chronic kidney disease stage 3 (disorder),XUh8m,D7-11102,1
10,15781000119107,0,Hypertensive heart AND chronic kidney disease ...,XUmqc,R-FB62B,1
11,731000119105,0,Chronic kidney disease stage 3 associated with...,XUmEB,R-FACD5,1
12,129151000119102,0,Chronic kidney disease stage 4 due to hyperten...,XUmo9,R-FB592,0
13,96711000119105,0,Hypertensive heart AND chronic kidney disease ...,XUmo5,R-FB58E,1
14,433146000,0,Chronic kidney disease stage 5 (disorder),XUh8o,D7-11103,1
15,285831000119108,0,Malignant hypertensive chronic kidney disease ...,XUlZX,D3-02732,1
16,698463001,0,At risk of chronic kidney disease (finding),XUmO7,R-FAF44,1
17,285851000119102,0,Malignant hypertensive chronic kidney disease ...,XUlZY,D7-1110D,1
18,444271000,0,Erythropoietin resistance in anemia of chronic...,XUjeb,DF-11471,1
19,431855005,0,Chronic kidney disease stage 1 (disorder),XUgnz,D7-110FF,1
20,129171000119106,0,Chronic kidney disease stage 3 due to hyperten...,XUmo8,R-FB591,0
21,285871000119106,0,Malignant hypertensive chronic kidney disease ...,XUlZa,D7-1110F,1
22,153851000119106,0,Malignant hypertensive chronic kidney disease ...,XUlZb,D7-11110,1
23,741000119101,0,Chronic kidney disease stage 2 associated with...,XUmEA,R-FACD4,1
24,96721000119103,0,Hypertensive heart AND chronic kidney disease ...,XUmo4,R-FB58D,1
25,96751000119106,0,Hypertensive heart AND chronic kidney disease ...,XUmo6,R-FB58F,1
26,711000119100,0,Chronic kidney disease stage 5 associated with...,XUmED,R-FACD7,1
27,8501000119104,0,Hypertensive heart and chronic kidney disease ...,XUmpJ,R-FB5DA,1
28,721000119107,0,Chronic kidney disease stage 4 associated with...,XUmEC,R-FACD6,1
29,96731000119100,0,Hypertensive heart AND chronic kidney disease ...,XUlZV,D3-0251A,1
30,431856006,0,Chronic kidney disease stage 2 (disorder),XUgo0,D7-11100,1
31,431857002,0,Chronic kidney disease stage 4 (disorder),XUgo1,D7-11101,1

In [9]:
# Export to check, and then will inactivate codes that are not relevant and re-upload as final reference table
df.to_excel("out/ckd_snomed.xlsx", index=False)

In [10]:

%%read_sql df

select
    *
from
    RWD_DB.RWD.PELICAN_E_SNOMED_CONCEPT
    
where ctvc_id ilike '%XUmvp%'

Query started at 12:57:19 PM India Standard Time; Query executed in 0.06 m

,concept_id,concept_status,fully_specified_name,ctvc_id,snomed_id,is_primitive
0,698941003,0,On examination - allodynia (finding),XUmVp,R-FB122,0
1,86172000,0,Structure of extensor carpi radialis brevis mu...,XUMVP,T-13832,1
2,86205005,0,Carbon oxysulfide (substance),XUMVp,C-10516,1
3,88276003,0,Haematosiphon inodorus (organism),XUMvp,L-61141,1
4,698915009,0,Main spoken language Oriya (finding),XUmVP,R-FB108,1
5,88238009,0,"Microbial smear, hanging drop technique (proce...",XUMvP,P3-50370,1

## Loinc codes for GFR

In [11]:
%%read_sql

create or replace table st_ckd_loinc as

    select
        loinc_num,
        component

    from RWD_DB.RWD.PELICAN_E_LOINC
    
    where loinc_num in ('50383-9', '69405-9', '70969-1')

Query started at 01:05:48 PM India Standard Time; Query executed in 0.13 m

                                     status
0  Table ST_CKD_LOINC successfully created.

In [12]:
%%read_sql
select * from st_ckd_loinc

Query started at 01:06:26 PM India Standard Time; Query executed in 0.05 m

  loinc_num                                          component
0   70969-1  Glomerular filtration rate/1.73 sq M.predicted...
1   69405-9     Glomerular filtration rate/1.73 sq M.predicted
2   50383-9               Glomerular filtration rate.predicted

In [13]:
%%read_sql

    select patient_id,
        loinc_num,
        obs_quan,
        unit,
        report_date
        
    from RWD_DB.RWD.PELICAN_LABORDER
    
    where loinc_num in ('50383-9', '69405-9', '70969-1')

Query started at 01:09:10 PM India Standard Time; Query executed in 0.25 m

                              patient_id loinc_num  obs_quan  unit report_date
0   C48B0BEC-EF0D-1BF0-AD40-3625697DC8C0   69405-9    205.28  None  2016-04-05
1   2EA0A42E-2A3A-F8A5-7E64-24F85A3FA20F   69405-9    262.49  None  2016-03-31
2   91D69E5F-A626-EBC1-8BB1-5F72F66778CA   69405-9     51.77  None  2016-10-04
3   618C2301-BD7E-F9E1-96EF-33EF848DF3A9   69405-9     65.32  None  2017-02-14
4   3C13A5F7-55EB-E0C8-5409-8329310E63AD   69405-9     46.41  None  2016-07-28
5   372B7AFC-F162-25E0-853E-2D60A249C0C8   69405-9    196.70  None  2017-10-03
6   FFFCF998-360E-2E86-C978-B52585E153FA   69405-9    108.94  None  2016-12-31
7   9A08D959-F258-7D2F-27FC-6C1664E63900   69405-9    106.96  None  2016-05-22
8   F33AC745-6433-3397-3DB0-0DA6A6B57CCD   69405-9    122.63  None  2017-02-05
9   7782E3F2-2A7A-0506-D3F9-849B9B9C9970   69405-9     61.03  None  2017-04-21
10  A3824C9F-45E8-E8CB-29FF-5D87B119039A   69405-9     96.00  None  2017-02-04
11  468BB8E8-6D72-4BA9-FA25-F87AC67846BA   69405-9    122.50  None  2016-07-30
12  3F4827F1-9EC8-2F31-1731-B68D8EAE1700   69405-9    118.50  None  2016-03-06
13  3F4827F1-9EC8-2F31-1731-B68D8EAE1700   69405-9    283.35  None  2016-06-11
14  4D3FAD9C-4314-5ABB-BFA2-CB9F1B547601   69405-9       NaN  None  2017-01-11
15  05A64FFC-1B44-91BA-CC4F-E1F6E68CA621   69405-9     84.33  None  2016-08-01
16  5F9EB837-CEBA-BC45-B47E-CC30C7454135   69405-9     48.85  None  2017-05-16
17  B68EB2FA-969A-67EA-1667-1342D8708F99   69405-9     76.63  None  2017-09-06
18  7DFCAB26-1519-4298-3B76-EC5AD0FE8E76   69405-9     88.36  None  2016-09-04
19  3F4827F1-9EC8-2F31-1731-B68D8EAE1700   69405-9    101.15  None  2017-11-22
20  50898021-69D2-A3D1-2039-1EB6C6DA7BD7   69405-9    167.21  None  2017-02-05
21  636B59A9-50A8-6942-59C1-3A1D8C18770E   69405-9     94.05  None  2016-04-04